### ISSUE TITLE
Doesn't work in Firefox if using mobile.twitter.com

### ISSUE THREAD

**Issue by tedyoung** [paulgb/Treeverse#31]
When viewing a tweet on the mobile website (mobile.twitter.com), the extension isn't active, e.g.:

    https://mobile.twitter.com/tastapod/status/1075743440632233984

For background, the reason I'm on a mobile.twitter.com subdomain is that bookmarked tweets only seem to be accessible via the mobile version of twitter and not the desktop version. 🤷‍♂️  Thanks Twitter!

**Comment by tedyoung** [comment]
Looks like https://github.com/paulgb/Treeverse/blob/master/src/background/common.ts#L1 needs to be updated to accept any subdomain (or at least `mobile`). There's a couple of other places where twitter.com is hard-coded, but the regex is probably the issue.

**Comment by paulgb** [comment]
Thanks for reporting this. I'll have a fix soon.

I like to keep notes in github issues as I investigate them, which follow.

It's a little more nuanced than I thought. Because of cross-domain security issues, the mobile.twitter.com page can't access twitter.com resources, so even if we initialize Treeverse on the mobile page it won't actually load any tweets.

One work-around is to redirect to the twitter.com site and *then* initialize Treeverse. This works on Firefox but not Chrome because the Chrome manifest doesn't include twitter.com so the implicit permission the user gives to act on the active tab when they click the button doesn't transfer to the redirected domain. A workaround is to add twitter.com permissions to the manifest but this breaks the PageStateMatcher -- basically, the Treeverse icon is lit up any time the user is on any twitter.com domain whether or not Treeverse can be invoked on that page, which is a bad user experience.

The other work-around is to prompt the user to redirect to twitter.com and then click the button again, thereby giving the extension permission again on the new domain. Unfortunately, `confirm` within the extension code seems to work in Chrome but not Firefox.

So where we end up is there is a nice clean one-click solution in Firefox and a reasonable two-click solution in Chrome, but neither works in the other browser. The best thing to do is probably just to implement both and use the one appropriate to the browser, it will just take a bit of refactoring to make this possible.

**Comment by tedyoung** [comment]
Ah, nothing is ever easy when it comes to permissions/cross-domain. Thanks for the notes, btw, it's really helpful.

**Comment by paulgb** [comment]
Ok, I figured out a two-click fix that works in both FF and Chrome. This will be fixed in v 2.4 (#32)
