### ISSUE TITLE
"This extension has been turned off as it's been marked unsafe by the Chrome Web Store."

### ISSUE THREAD

**Issue by HenkPoley** [paulgb/treeverse#91]
What is the issue ?

![image](https://user-images.githubusercontent.com/2931213/175241960-ca17751e-c0dd-4dfd-b52f-3d886681126e.png)

**Comment by paulgb** [comment]
Thanks for bringing this to my attention, @HenkPoley and @kstudnik. I'd apparently received emails about it, but had been so busy with other things I neglected them. I've narrowed the issue down to the `contextMenus` permission being requested by the extension but not used. I must have either used it at one point, or experimented with it and forgot to take it out. In any case, the fix was simply removing it, which I have done and re-submitted.

Assuming the review passes, Treeverse should be back in the app store shortly (they say up to a few weeks, but my experience has been ~hours).

Chrome is also getting rid of the background worker functionality that Treeverse uses, which is unfortunate from Treeverse's point of view (but ultimately a good thing for extension security). This won't happen until next year, but it will likely break Treeverse again. Now that Twitter has an API with replies, I might be able to build this as a more traditional web service that uses the API.
